question_data = [
    {"text": "What is the capital of France?", "answer": "Paris"},
    {"text": "What is 2 + 2?", "answer": "4"},
    {"text": "What is the largest planet in our solar system?", "answer": "Jupiter"},
    {"text": "Who wrote 'Hamlet'?", "answer": "Shakespeare"},
    {"text": "What is the boiling point of water?", "answer": "100 degrees Celsius"},
    {"text": "What is the capital of Japan?", "answer": "Tokyo"},
    {"text": "What is the smallest prime number?", "answer": "2"},
    {"text": "Who painted the Mona Lisa?", "answer": "Leonardo da Vinci"},
    {"text": "What is the chemical symbol for gold?", "answer": "Au"},
    {"text": "What is the hardest natural substance on Earth?", "answer": "Diamond"},
    {"text": "What is the largest mammal?", "answer": "Blue Whale"},
    {"text": "What is the currency of the United Kingdom?", "answer": "Pound Sterling"},
    {"text": "What is the main ingredient in guacamole?", "answer": "Avocado"},
    {"text": "What year did the Titanic sink?", "answer": "1912"},
    {"text": "Who is known as the 'Father of Computers'?", "answer": "Charles Babbage"},
    {"text": "What is the largest desert in the world?", "answer": "Sahara"},
    {"text": "What is the smallest country in the world?", "answer": "Vatican City"},
    {"text": "What planet is known as the Red Planet?", "answer": "Mars"},
    {"text": "What is the main language spoken in Brazil?", "answer": "Portuguese"},
    {"text": "Who discovered penicillin?", "answer": "Alexander Fleming"},
    {"text": "What is the tallest mountain in the world?", "answer": "Mount Everest"},
    {"text": "What is the chemical formula for water?", "answer": "H2O"},
    {"text": "Who wrote '1984'?", "answer": "George Orwell"},
    {"text": "What is the largest ocean on Earth?", "answer": "Pacific Ocean"},
    {"text": "What is the capital of Italy?", "answer": "Rome"},
    {"text": "What is the fastest land animal?", "answer": "Cheetah"},
    {
        "text": "What is the main ingredient in traditional Japanese miso soup?",
        "answer": "Miso paste",
    },
    {
        "text": "Who was the first person to walk on the moon?",
        "answer": "Neil Armstrong",
    },
    {"text": "What is the largest organ in the human body?", "answer": "Skin"},
    {"text": "What is the capital of Canada?", "answer": "Ottawa"},
    {
        "text": "What is the most widely spoken language in the world?",
        "answer": "Mandarin Chinese",
    },
    {"text": "What is the main ingredient in hummus?", "answer": "Chickpeas"},
    {
        "text": "Who painted the ceiling of the Sistine Chapel?",
        "answer": "Michelangelo",
    },
    {"text": "What is the capital of Australia?", "answer": "Canberra"},
    {"text": "What is the largest continent?", "answer": "Asia"},
    {"text": "What is the chemical symbol for oxygen?", "answer": "O"},
    {"text": "Who wrote 'Pride and Prejudice'?", "answer": "Jane Austen"},
    {
        "text": "What is the smallest bone in the human body?",
        "answer": "Stapes (in the ear)",
    },
    {"text": "What is the capital of Germany?", "answer": "Berlin"},
    {
        "text": "What is the main ingredient in a traditional Greek salad?",
        "answer": "Feta cheese",
    },
]

computer_science_questions = {
    "response_code": 0,
    "results": [
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science: Computers",
            "question": "A Mac is not a PC",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science: Computers",
            "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science: Computers",
            "question": "Ada Lovelace is often considered the first computer programmer.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science: Computers",
            "question": "Linus Torvalds created Linux and Git.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science: Computers",
            "question": "The Windows ME operating system was released in the year 2000.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science: Computers",
            "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science: Computers",
            "question": "Time on Computers is measured via the EPOX System.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science: Computers",
            "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science: Computers",
            "question": "The logo for Snapchat is a Bell.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science: Computers",
            "question": "RAM stands for Random Access Memory.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ],
}
