print("Notes from Day 1")
print("The print statement is used to output strings")
print("Strings are strings of characters")
print("String Concatenation is done with the" + " " + "sign")
print("New lines can be created with a\nand the letter ")
input("What is your name?")
print("Hello, " + input("What is your name?") + "!")
