print("welcome to the tip calculator")
bill = float(input("What was the total bill? $"))
tip = int(input("What percentage tip would you like to give? 10, 12, or 15? "))
people = int(input("How many people to split the bill? "))
bill_with_tip = bill + (bill * tip / 100) 
print(f"Each person should pay: ${round(bill_with_tip / people, 2)}")              
